Update linux recipes
Pelagicore/meta-arp pull request #6
Opened 2018-05-17 08:26 UTC by linusnielsen

The linux-yocto recipe is obsolete, so I removed it. Then I added a linux-intel recipe to build the altera-tse driver.

2018-05-17 09:14 UTC, TSAnsari commented
Ok, I will make a build test with these changes and once it passes, this can be delivered.

2018-05-18 13:39 UTC, TSAnsari approved these changes
The test build worked. So you can deliver this.

2018-05-23 07:52 UTC, thenor commented on recipes-kernel/linux/linux-intel/altera-tse.cfg
> +CONFIG_ALTERA_TSE=m
Would it be possible to add some information on what this means? :smiley:

2018-05-23 07:53 UTC, thenor commented
Please start using the s-flag with "git commit" so the commits are signed off. According to our contributing guidelines.

2018-05-23 07:59 UTC, thenor requested changes
Update the commit messages with the signed-off info and I will be happy.

2018-05-23 09:45 UTC, linusnielsen commented
One force-push later, the commits now have a Signed-off-by line.

2018-05-23 13:11 UTC, thenor approved these changes
Thanks!

2018-05-24 07:41 UTC, merged