Add arp-driver recipe
Pelagicore/meta-arp pull request #7
Opened 2018-05-24 07:53 UTC by TSAnsari

Signed-off-by: tansari <tansari@luxoft.com>

2018-05-24 09:19 UTC, thenor approved these changes

2018-05-28 06:43 UTC, erikboto commented on recipes-kernel/arp-driver/arp-driver_git.bb
> +SRC_URI = "git://github.com/TSAnsari/arp-driver.git;protocol=https;branch=master"
Why would the code be hosted on your private fork? Also the SRCREV doesn't seems to exist.

2018-05-28 06:59 UTC, sashko commented
In addition to Erik's comment, I am not sure I understand what the "ARP driver kernel module" is -- isn't it supposed to be a bunch of kernel modules with different drivers needed for the ARP?

2018-05-28 06:59 UTC, sashko requested changes
recipe is broken

2018-05-28 07:21 UTC, TSAnsari commented on recipes-kernel/arp-driver/arp-driver_git.bb
> +SRC_URI = "git://github.com/TSAnsari/arp-driver.git;protocol=https;branch=master"
The revision of arp-driver repo which this points to is not yet delivered, so I used my private fork to test this. Once the arp-driver changes are delivered to master, then I will update this to point to that revision. Will definitely not push with this pointing to private fork.

2018-05-28 07:30 UTC, frznlogic commented on recipes-kernel/arp-driver/arp-driver_git.bb
> +SRC_URI = "git://github.com/TSAnsari/arp-driver.git;protocol=https;branch=master"
Please add a WIP: prefix to the PR in that case to indicate that it is Work In Progress.

2018-05-31 08:27 UTC, TSAnsari commented
@sashko This is how ARP team has structured the drivers at the moment. All exists under one module name arp-driver. If it changes in the future then we need to create separate recipies for each of them. Hope thats what you mean?

2018-06-12 13:32 UTC, merged